server:
  port: 8088

guidingdog:
  upstream:
    rosbridge: ws://localhost:9090
    video: http://localhost:8080

spring:
  webflux:
    base-path: /
management:
  endpoints:
    web:
      exposure:
        include: health,info